### ISSUE TITLE
CLIClientException at runtime

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#16] opened 2015-05-11 19:04 UTC
I started running the script on my real (not sample) project, and I got a CLIClientException
![npe1](https://cloud.githubusercontent.com/assets/3940962/7572810/f602d8e8-f7ee-11e4-80f2-2e2380ed5302.PNG)
![npe2](https://cloud.githubusercontent.com/assets/3940962/7572811/f607bc0a-f7ee-11e4-98b7-d4387a6e2048.PNG)

 at runtime.  I will poke into this more tomorrow, but thought I'd post today in case there was a known solution.

**Comment by WtfJoke** [comment] 2015-05-11 19:33
Hmm well against such Exceptions I cant do much, there are internal exceptions, which are caused by the cli of rtc itself.....
You maybe can try to post it as a defect at [IBM] (https://jazz.net/jazz/web/projects/Rational Team Concert) directly or try to ask it on https://jazz.net/forum/questions/ask/

Do you get different results if you remove -w WORKSPACE?

**Comment by ljhaywar** [comment] 2015-05-12 12:53
I've done some more poking around this morning, and I haven't gotten very far.  I tried removing the workspace from the command, and I still got the error.  
![withoutworkspace](https://cloud.githubusercontent.com/assets/3940962/7587431/1dc9fdd0-f884-11e4-846d-41731da3c75f.PNG)

I opened the Accept log, and I'm seeing:

Following workspaces still have conflicts after accept:
 [myworkspacename]
Run 'lscm resolve conflict' or 'lscm show conflicts' or 'lscm show status' for help in resolving the conflicts.

So I modified the script to run 'lscm show conflicts' and 'lscm resolve conflict --auto-merge' and both times I got the same exception when running the commands.

I'll keep working with it.

**Comment by WtfJoke** [comment] 2015-05-12 19:35
I've been there too... The thing is, in my opinion the RTC CLI is not really made for resolving merges. The best way to handle conflicts is to load the workspace using eclipse and check whats wrong using the Pending Changes View. However, sometimes it can happen that you break the whole workspace by creating an irreversible state (if you try to discard/undo stuff and get exceptions like cannot undo/discard cause would create fork conflict...). If you experience really nasty conflicts, always create a duplicate of your workspace before you make any (wrong) move and dont want to do the start migration from the beginning.

The provided order of the changes (from the compare command) is sometimes wrong. You can verify if its wrong by going to the history tab and press the button show in flow-target and if the orders doesnt match you might have an unsolvable problem. In this case its the best way if you use the way with the provided history (UseProvidedHistory = True). More details can be found in the wiki here: https://github.com/WtfJoke/rtc2git/wiki/Getting-your-History-Files

**Comment by ljhaywar** [comment] 2015-05-13 12:05
I've been running the script with UseProvidedHistory = True.

My understanding of the what the script is doing:
1.  Create a new repository workspace.
2.  Accept changes one by one into the workspace, beginning with the oldest change.
I'm not sure why the script would be hitting merge conflicts if the script is not making changes to the code in the workspace.  Why am I getting these merge conflicts?

If I resolve the merges manually in Eclipse, do I need to deliver merges or are they ok in the Outgoing Changes view?  

When I hit the merge conflict error, the script asks me to "Press Enter to try to accept it with next changeset together, press any other key to skip this changeset and continue."  It seems like when I hit the error I should kill the script, manually do the merge in Eclipse, and run the script again using resume so that the changes are all correctly copied to Git.  Is that right?

**Comment by ljhaywar** [comment] 2015-05-13 12:29
Also, regarding resolving the merging errors, is there a reason why Resolving with Proposed would not be safe/correct?

**Comment by WtfJoke** [comment] 2015-05-13 19:48
Ok good that you use it, just by that you avoid some merge conflicts.
Yes your understanding what the script is doing is correct. I struggled with the same thoughts (2.)... I couldnt believe why there should be merge conflicts. I wasnt able to understand it completly, however was able to get more or less an explaination.

Example:
1. Person A does some work on FooBar.java based on version 1
2. Person B starts working too on FooBar.java also based on version 1
3. Person A decides to a couple of changes and delivers version 2 and version 3.
4. Person B wants to deliver the stuff and receive a mergeconflict, which he needs to solve, afterwards he is gonna deliver the changes (including the merge)

Here is a picture from the history of a file how it will look like. (pay attention at the colored lines):
![Here is a picture how it will look like, pay attention at the colored lines](https://cloud.githubusercontent.com/assets/7139697/7618043/a92bd502-f9af-11e4-929f-eff2648be237.png)

In the moment youre accepting the changeset where the red 2 is, you have accepted already accepted the two changeset before and arent based on version 1 anymore. So if you accept it, rtc doesnt know how to handle it cause you arent based on version 1 (which the changeset was originally based from), therefore getting a merge-conflict. 

The solution here is instead of accepting only 1 changeset, accepting both the one marked with the red 2 and the one who "travels" back to the red square.

In my personal opinion its still strange, how these situation can occur or how rtc handles changeset like that.

Was kinda long explaination... Hope it helped a bit.


Regarding merging: Im not sure.. To be honest I dont trust the merge function that much anymore. I experience some bad situations. I think its still the best way to deal with merge conflicts manually and decide based on the situation whats best.

**Comment by WtfJoke** [comment] 2015-05-13 20:17
About the script prompt. There are two. The one you mentioned is a semi-automatic solution for the mentioned problem in my previous comment.

It works like this:
Based on the informatino it thinks its a merge changeset and then user can decide if its a merge changeset or not,  you can hit enter that it accepts both and like that "solves" the merge conflict.

If it not thinks its a merge changeset then you get prompt "Press Enter to continue or any other key to exit the program and rerun it with resume". Then you can do it like you described it. You could also instead of killing the script reload your workspace in the folder where its loaded and then press Enter

**Comment by ljhaywar** [comment] 2015-05-14 11:39
Thanks for the detailed explanation!  When I open the Pending Changes view in RTC, the changeset with the conflict is often about 10 to 20 changesets down.  If I accept a big group of changes together in RTC, will the script convert all of those changes to a Git commit?

Can you provide more details on how to do this: You could also instead of killing the script reload your workspace in the folder where its loaded and then press Enter.  Are you saying to run commands in the same shell where the script is running to reload the workspace?  If so, how would I resume the script?

**Comment by WtfJoke** [comment] 2015-05-14 13:06
> If I accept a big group of changes together in RTC, will the script convert all of those changes to a Git commit?

No it wont. It will be in the git repository but connected with wrong informations.

If you resume the script all the changes will get commited with the next changeset, which has nothing to do with the big group of changesets you accepted before, so usually thats not what you want. 

>If I resolve the merges manually in Eclipse, do I need to deliver merges or are they ok in the Outgoing Changes view? 

You dont need to deliver them, as long they are in unresolved or outgoing changes its fine

> Are you saying to run commands in the same shell where the script is running to reload the workspace? If so, how would I resume the script?

No you can and should use another shell to reload the workspace (at least im not aware of how you run the python script and do something other in the same shell). In this case you dont need to resume at all, since you can skip this changeset.
Maybe its not the favorable solution. It was just the way how I did it sometimes. I resolved the merge in the eclipse workspace, reloaded it in the folder where the migration takes place and then used the appropriate git command (git add -A, git commit -m .... ) to commit these changes. Afterwards I switched back to the script and skipped the change by either Pressing Enter or another key (if Msg is "Press Enter to continue or any other key to exit the program and rerun it with resume" --> Enter, if Msg is "Press Enter to try to accept it with next changeset together, press any other key to skip this changeset and continue." --> Another key)

**Comment by ljhaywar** [comment] 2015-05-14 13:30
Thanks for continuing to provide such fast responses!  To follow up - if I resolve a conflict manually in RTC, I need to open a new shell and manually commit the files before resuming the script.  Is that right?

**Comment by WtfJoke** [comment] 2015-05-14 13:46
If you mean with commit the git part, then yes, thats correct. :)

**Comment by ljhaywar** [comment] 2015-05-14 14:03
Thinking about this more -- if I manually resolve the conflict in RTC without manually committing the files, the files will be included with the next commit--so the changes will still be in the git repository just with the wrong information associated with it.  Is that right?

When you manually committed the files to the git repo, how did you know what info to include in the commit (date, message, author, etc)?

**Comment by WtfJoke** [comment] 2015-05-14 14:39
> Thinking about this more -- if I manually resolve the conflict in RTC without manually committing the files, the files will be included with the next commit--so the changes will still be in the git repository just with the wrong information associated with it. Is that right?

Yes

> When you manually committed the files to the git repo, how did you know what info to include in the commit (date, message, author, etc)?

In case the accept is not succesfull and the next change is not a merge changeset it gets displayed before in the console: "Apropriate git commit command: git commit -m ..." (see https://github.com/WtfJoke/rtc2git/blob/develop/rtcFunctions.py#L189)

So just do a git add -A and then the commit using the previous displayed command.
As alternative you can do the same manually, because all the informations are given on the log (author, date, comment etc..)

**Comment by ljhaywar** [comment] 2015-05-21 11:07
I was running the script, and it hit a conflict.  I stopped the script, manually resolved the conflict in Eclipse, and restarted the script.  The script reported:
"The following resources had uncommitted changes and were overwritten"
Does this mean the changes that I manually resumed and brought back in to my workspace were lost and not committed to the git repo?

**Comment by WtfJoke** [comment] 2015-05-21 13:44
No, everything is fine. Its like a confirmation that the resolved conflict has been applied (The local copy of your workspace in eclipse has replaced the local copy of the migration, where the conflict wasnt solved)

**Comment by ljhaywar** [comment] 2015-05-21 14:02
Ah, makes sense.  Thank you!

**Comment by WtfJoke** [comment] 2015-05-21 14:33
But usually when this happens, you need to make the git add / git commit on your own. Else it will get commited with the next commit (still in git repo, but probably with wrong information). In this case usually I reload the workspace on my own (after resolving conflicts) in this folder before resuming the script to see such stuff.

**Comment by WtfJoke** [comment] 2015-05-26 06:39
I'll close this issue, cause I have no power about fixing the internal cli of rtc (see https://github.com/WtfJoke/rtc2git/issues/16#issuecomment-101026392)

If you think, I should do something here, feel free to reopen it and tell me what I can do for you :smile:

**Closed by WtfJoke** 2015-05-26 06:39 UTC
Labels: help wanted, question

**Comment by ljhaywar** [comment] 2015-06-01 18:19
I agree this issue can be closed.  The root problem was a conflict.  The solution is to resolve it manually in Eclipse.  An even cooler solution would be to update the script to Resolve with Proposed when a conflict arises.

**Comment by WtfJoke** [comment] 2015-06-01 18:53
Ok, thanks for the update.

> An even cooler solution would be to update the script to Resolve with Proposed when a conflict arises.

 Lately I was thinking about whats the best way to deal with conflicts. I thought about auto resolve... Quite unsure whats the best way.

**Comment by jacobilsoe** [comment] 2015-06-01 21:59
I still believe conflicts can be avoided altogether if enough change sets are accepted together.

**Comment by WtfJoke** [comment] 2015-06-02 06:28
> I still believe conflicts can be avoided altogether if enough change sets are accepted together.

Just based on the fact, that everything is the repo/stream has been once delivered/merged in some way, it should be like that.
