### ISSUE TITLE
Problem with login running from windows using scm

### ISSUE THREAD

**Issue by lmcarreiro** [WtfJoke/rtc2git#121] opened 2017-05-30 15:12 UTC
Using scm on Windows 7, I had problems with login

Had to change the line:
`shell.execute("%s login -r %s -u '%s' -P '%s'" % (config.scmcommand, config.repo, config.user, config.password))`

Into:
`shell.execute("%s login -r %s -u %s -P %s" % (config.scmcommand, config.repo, config.user, config.password))`

And it worked fine. I didn't make a PR because I don't know how it behaves using lscm instead of scm, or in other systems.

**Comment by WtfJoke** [comment] 2017-06-12 17:42
Thanks for your information. I dont know why you experience this error... 
Do you have windows or linux?
Initially it was without quotes but was added for special chars in passwords here: https://github.com/rtcTo/rtc2git/pull/96

I hope you understand that I close this issue, as I cannot reproduce it on my system and you found a relative easy workaround. :)
If other users experience the same problem, they can reopen this bug.

**Closed as completed by WtfJoke** 2017-06-12 17:42 UTC

**Comment by lmcarreiro** [comment] 2017-06-12 18:33
I'm in windows 7 system.

I had to change another line:
`command = "scm --show-alias n --show-uuid y list baselines --components %s -r %s -u %s -P '%s' -m 20000" % \`

To:
`command = "scm --show-alias n --show-uuid y list baselines --components %s -r %s -u %s -P %s -m 20000" % \`
